#+TITLE:  Advent of Code 2017
#+AUTHOR: Diego Vicente Martín
#+EMAIL:  mail@diego.codes

This repository contains all the code for my solution (written in Python 3) for
solving all the puzzles of the [[http://adventofcode.com/2017][Advent of Code 2017]] challenges. Although not in
a competitive way (living in UTC+01 is quite a handicap, since the challenges
are released at 6AM), I was able to complete all the challenges by December
25th.

Some of the challenges may require a bit of refactoring and optimization, and I
expect to write a bit more on it soon (whether on this repository or on a blog
post); but the code can be interesting for some people and I decided to release
it as soon as possible. Feel free to open an issue or contact in case of doubt.

Each of the challenges are written in their file, named =dayXX.py=. To run each
of them, be aware that most of them require an input (mine are gathered under
the =data= folder), and to properly work must be run from the root of the
repository:

#+BEGIN_SRC sh
cd advent-of-code-2017
python3 src/day09.py
#+END_SRC
